config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#show', page: 'welcome'
  resources :users, only: [:new, :create, :index, :show]
  resources :sessions, only: [:new, :create, :destroy]
  get '/login', to: 'sessions#new'
  resources :recipes do
    resources :steps, shallow: true, except: [:new]
    resources :comments, shallow: true, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :steps, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_attached_file :image, styles: { medium: "500x500>", thumb: "250x250>" }, presence: true
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/step.rb
class Step < ApplicationRecord
  belongs_to :recipe
end

app/models/user.rb
class User < ApplicationRecord
    has_attached_file :image, styles: { medium: "500x500>", thumb: "250x250>" }, presence: true
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
    has_many :recipes, dependent: :destroy
    has_secure_password
    validates :email, presence: true, uniqueness: true
end
 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private 
    helper_method :current_user

    def current_user
      @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
    end

    def authorize
      redirect_to login_path, alert: 'Not authorized - you must be logged in!' if current_user.nil?
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def show
        render "pages/#{params[:page]}"
    end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

    def new 
        @recipe = Recipe.new
    end

    def show 
        @recipe = Recipe.find(params[:id])
        @step = Step.new
    end

    def create
        @recipe = Recipe.new(params.require(:recipe).permit(:title, :category, :image))
        @recipe.user = current_user
         if @recipe.save
            redirect_to recipe_path(@recipe)
         else
            render :new
         end
    end


    def destroy
        @recipe = Recipe.find(params[:id])
        @recipe.destroy
        redirect_to user_path(current_user)
    end

    def edit
        @recipe = Recipe.find(params[:id])
    end
    
    def update 
        @recipe = Recipe.find(params[:id])
        @recipe.update_attributes(params.require(:recipe).permit(:title, :category))
        redirect_to user_path(current_user)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
    
    end

    def create
        user = User.find_by(email: params[:email])
        if user && user.authenticate(params[:password])
            session[:user_id] = user.id
            redirect_to user_path(current_user)
        else
            flash.now.alert = 'Invalid login credentials - try again!'
            render :new
        end
    end

    def destroy
        session[:user_id] = nil
        redirect_to root_path, notice: "Logged out!"
    end
end

app/controllers/steps_controller.rb
class StepsController < ApplicationController
    def create
        @step = Step.new(params.require(:step).permit(:content))
        @step.recipe_id = params[:recipe_id]
        @step.save
        redirect_to recipe_path(params[:recipe_id])
    end

    def destroy
        @step = Step.find(params[:id])
        recipe = @step.recipe
        @step.destroy
        redirect_to recipe_path(recipe)
    end

    def edit
        @step = Step.find(params[:id])
    end
    
    def update 
        @step = Step.find(params[:id])
        @step.update_attributes(params.require(:step).permit(:content))
        redirect_to recipe_path(@step.recipe)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = User.all
  end
  
  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    @recipes = @user.recipes
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "You have successfully created an account!"
      redirect_to user_path(current_user)
    else
      render :new
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :image, :specialty, :bio)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChefAmatuer</title>
    <%= csrf_meta_tags %>
    <script defer src="https://use.fontawesome.com/releases/v5.0.10/js/all.js" integrity="sha384-slN8GvtUJGnv6ca26v8EzVaR9DC58QEwsIk9q1QXdCU8Yu8ck/tL/5szYlBbqmS+" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/css/materialize.min.css">
    <script defer src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/js/materialize.min.js"></script>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Righteous" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Great+Vibes|Lobster" rel="stylesheet">
  </head>

  <body>
    <% if current_user %>
    <header>
      <h1 class="pgsh">Chef Amateur</h1>
      <i class="material-icons logo">local_dining</i>
          <nav class="nav-extended">
              <div class="nav-content">
                <ul class="tabs tabs-transparent">
                  <li class="tab"><%= link_to "My Recipes", user_path(current_user)%></li>
                  <li class="tab"><%= link_to "All Chefs", users_path%></li>
                  <li class="tab"><%= link_to 'Log Out', session_path('dummy'), method: :delete, :class => 'logout' %></li>
                </ul>
              </div>
            </nav>
    </header>
    <% end %>
    <%= yield %>
    <footer>
      <p>&copy; Chef Amateur By Jesse Aguirre GA-DT-57</p>
      <div class="web">
        <a href="https://github.com/Jaguirre123?tab=repositories" target='blank' class="icons"><span class="fab fa-github-square"></span></a>
        <a href="https://www.linkedin.com/in/jesse-aguirre-405b47156/" target='blank' class="icons"><span class="fab fa-linkedin"></span></a>
      </div>
    </footer>
  </body>
</html>

app/views/pages/welcome.html.erb
<div id="mainpg">
    <center>
        <h2 class="pgsh">Welcome to</h2>
        <h1 class="pgsh">Chef Amatuer</h1>
            <p class="welcomeP">Create an account and post your best recipes for others to try. <br> Check out other chef accounts and and try there recipes.</p>
        <hr>
    </center>

    <p class="welinks">

        <%= link_to 'Log In', login_path, :class => 'first_links' %>
        &nbsp;&nbsp;|&nbsp;&nbsp;
        <%= link_to 'Sign Up', new_user_path, :class => 'first_links' %>

    </p>
</div>

app/views/recipes/edit.html.erb
<h1>Edit Recipe Name</h1>
<hr>

<%= form_for @recipe do |f| %>
<div class="input-field col s6">
    <%= f.text_field :title%>
    <%= f.text_field :category%>
    <div class="btnCenter">
        <%= f.submit 'Edit Recipe', class: 'btn'%>
    </div>
</div>
<% end %>

app/views/recipes/index.html.erb
<h3><%= current_user.name %></h3>
  <%= link_to "New Recipe", new_recipe_path %>
<table class="table">
    <tbody>
    <tr>
        <th>Recipe Title</th>
    </tr>
    <% current_user.recipes.each do |recipe| %>
        <tr>
            <td><%= link_to recipe.title,  recipe_path(recipe) %></td>
        </tr>
    <% end %>
    </tbody>
</table>

app/views/recipes/new.html.erb
<h1>New recipe</h1>
<hr>
<%= form_for @recipe, html: {multipart: true} do |f| %>
<div class="input-field col s6">
    <%= f.label :title %>
    <%= f.text_field :title, required: true %>
</div> 
<div class="input-field col s6">
    <%= f.label :category %>
    <%= f.text_field :category, required: true%>
</div>
<div class="input-field col s6">
    <%= f.label "Recipe Image" %>
    <%= f.file_field :image, required: true, class: 'fileInput'%>
</div>
    <hr>
    <div class="btnCenter">
         <%= f.submit 'Create Recipe', class: 'btn'%>
    </div>
<% end %>

app/views/recipes/show.html.erb
<div class="recipe">
    <h4 class="meals"><%= @recipe.title %></h4>
    <hr>
    <%= image_tag @recipe.image, class:'recipeImgs' %>
</div>
<% if @recipe.steps.count == 0 %>
    <h4 class="noStep">No Steps for <%= @recipe.title %> Recipe Yet</h4>
    <hr>
<% else %>
    <table class="table highlight">
        <tbody>
            <tr>
                <th>Steps</th>
                <th>Decription</th>
                <% if current_user == @recipe.user %>
                    <th>Edit Step</th>
                    <th>Delete Step</th>
                <% end %>
            </tr>
            <% @recipe.steps.each_with_index do |step, i| %>
                <tr>
                    <td><%= i + 1 %></td>
                    <td><%= step.content%></td>
                        <% if current_user == @recipe.user %>
                            <td>
                                <%= link_to edit_step_path(step), class: "btn" do %>
                                <i class="material-icons">edit</i> 
                                <% end %>
                            </td>
                            <td>
                                <%= link_to step_path(step), method: :delete, :data=> {:confirm=>'Are you sure you want to delete this step?'}, class: "btn" do %>
                                <i class="material-icons">delete_forever</i>
                                <% end %>
                            </td>
                        <% end %>
                </tr>
            <% end %>
        </tbody>
    </table>
<% end %>
<% if current_user == @recipe.user %>
    <%= form_for [@recipe, @step] do |f| %>
        <div class="input-field col s6">
            <%= f.label "Add a step" %> 
            <%= f.text_field :content%>
            <div class="btnCenter">
                 <%= f.submit 'Add Step', class: 'btn' %>
            </div>
        </div>
    <% end %>
<% end %>

app/views/steps/edit.html.erb
<h1>Edit Step</h1>
<hr>
<%= form_for @step do |f| %>
<div class="input-field col s6">
    <%= f.text_field :content%>
    <div class="btnCenter">
        <%= f.submit "Edit Step", class: "btn" %>
    </div>
</div>
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/index.html.erb
<h1>All Chefs</h1>

<hr>
<table class="table highlight">
  <thead>
    <tr>
      <th><i class="material-icons">person</i> Name</th>
      <th><i class="material-icons">restaurant</i> Specialty</th>
      <th><i class="material-icons">local_dining</i> Recipes</th>
      <th><i class="material-icons">email</i> email</th>
      <th colspan="3"></th>
    </tr>
  </thead>


  <tbody>
    <% @user.each do |user| %>
      <tr>
        <td><%= link_to user.name, user_path(user) %></td>
        <td><%= user.specialty %></td>
        <td><%= user.recipes.count %></td>
        <td><%= user.email %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<%= link_to root_path do %>
  <i class="material-icons arrows">arrow_back</i>
<% end %>

<h1>Sign Up</h1>
<hr>
 <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<%= form_for @user do |f| %>
  <div class="input-field col s6">
    <%= f.label :name %>
    <%= f.text_field :name, required: true %>
  </div>
  <div class="input-field col s6">
    <%= f.label :email %>
    <%= f.text_field :email, required: true %>
  </div>
  <div class="input-field col s6">
    <%= f.label :password %>
    <%= f.password_field :password, required: true %>
  </div>
  <div class="input-field col s6">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, required: true %>
  </div>
  <div class="input-field col s6">
    <%= f.label :specialty %>
    <%= f.text_field :specialty, required: true %>
  </div>
  <div class="input-field col s6">
    <%= f.label :bio %>
    <%= f.text_field :bio %>
  </div>
  <div class="input-field col s6">
    <%= f.label "User Image" %>
    <%= f.file_field :image, required: true, class: 'fileInput'%>
  </div>
  <hr>
  <div class="btnCenter">
    <div class="actions">
      <%= submit_tag "Sign Up", class: 'btn' %>
    </div>
  </div>
<% end %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>


    <div class="card">
        <div class="card-image waves-effect waves-block waves-light">
            <%=image_tag @user.image, class:'userImgs' %>
            <hr>
        </div>
        <% if current_user == @user %> 
            <div class="card-content">
                <span class="card-title activator grey-text text-darken-4"><h3 class="userNames"><%= @user.name %></h3><i class="material-icons right">more_vert</i></span>
            </div>
        <% else %>
              <div class="card-content">
                <span class="card-title activator grey-text text-darken-4"><h3 class="userNames">Welcome to <%= @user.name %>'s Kitchen</h3><i class="material-icons right">more_vert</i></span>
            </div>
        <% end %>
        <div class="card-reveal">
            <span class="card-title grey-text text-darken-4"><%= @user.name %>'s Bio<i class="material-icons right">close</i></span>
            <hr>
            <p><%= @user.bio %></p>
        </div>
   </div>
   <% if current_user == @user %> 
        <center class="recCenterTag">
            <%= link_to new_recipe_path, class: 'newRecLink' do %>
                <i class="material-icons">add</i> New Recipe
            <% end %>
        </center>
    <% end %>
<% if @user && @user.recipes.count == 0 %>
    <h3 class="noRec">There Are No Recipes</h3>
<% else %>
<table class="table highlight">
    <tbody>
    <tr>
        <th>Recipe Title</th>
        <th>Category</th>
        <% if current_user == @user %>
            <th>Edit</th>
            <th>Delete</th>
        <% end %>
    </tr>

    <% @user.recipes.each do |recipe| %>
        <tr>
            <td><%= link_to recipe.title, recipe_path(recipe) %></td>
            <td><%= recipe.category %></td>
            <% if current_user == @user %>
                <td>
                    <%= link_to edit_recipe_path(recipe), class: "btn" do %>
                        <i class="material-icons">edit</i>
                    <% end %>
                </td>
                <td>
                    <%= link_to recipe_path(recipe), method: :delete, :data=> {:confirm=>'Are you sure you want to delete this recipe?'},  class: "btn" do %>
                        <i class="material-icons">delete_forever</i>
                    <% end %>
                </td>
            <% end %>
        </tr>
    <% end %>
    </tbody>
</table>
<% end %>